# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Homepage for Brian Pointer
email: myfirstandlastname-at-gmail-dot-com
description: > # this means to ignore newlines until "baseurl:"
  Web presence of Brian Pointer. Projects, musings, and various goings-on. A work in progress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brianpointer.com" # the base hostname & protocol for your site
twitter_username: brianpointer
github_username:  brianpointer

# Build settings
markdown: kramdown
